name: env-test
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Secret is set"
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH }}
