name: env-test
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Secret is ${TEST_SECRET}"
        env:
          TEST_SECRET: ${{ secrets.PGPASSWORD }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH }}
